### ISSUE TITLE
 I need your help

### ISSUE THREAD

**Issue by francisguchie** [bharathcgowda/Fineract#3]
@bharathcgowda  

i have this error while triying to get pentaho into the latest build - wanted to raise the PR
How can i isolate the duplicates fix this error?? I need help 

org.opentest4j.AssertionFailedError: 3 Classpath duplicates detected:
overview.html
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/org.mnode.ical4j/ical4j/3.0.19/5aa648ce509674af21b3a46ce1efb5aa3300b651/ical4j-3.0.19.jar!/overview.html
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/3.9.1-GA/1d99d2fa5cfaadfeb6d50b46001b1b8c04b77670/pentaho-reporting-engine-classic-core-3.9.1-GA.jar!/overview.html
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/3.9.1-GA/24114228757a9325f4b4e4899471413f6ae90d2c/pentaho-reporting-engine-classic-extensions-3.9.1-GA.jar!/overview.html
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-library/libfonts/1.2.8/8d20d16c7b4022480df8fb8aa7c51f6357ff1817/libfonts-1.2.8.jar!/overview.html
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-library/libserializer/1.2.8/52d4ccad3fa757ec040a3da34314d08c4a071332/libserializer-1.2.8.jar!/overview.html
classic-engine.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions/3.9.1-GA/24114228757a9325f4b4e4899471413f6ae90d2c/pentaho-reporting-engine-classic-extensions-3.9.1-GA.jar!/classic-engine.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-classic-extensions-scripting/3.9.1-GA/174cce581a247680f24404e9ed6ef1fbfb53ae29/pentaho-reporting-engine-classic-extensions-scripting-3.9.1-GA.jar!/classic-engine.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/3.9.1-GA/671508e5f7b038b19ddbdf34914eab87bbb646ee/pentaho-reporting-engine-wizard-core-3.9.1-GA.jar!/classic-engine.properties
loader.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-classic-core/3.9.1-GA/1d99d2fa5cfaadfeb6d50b46001b1b8c04b77670/pentaho-reporting-engine-classic-core-3.9.1-GA.jar!/loader.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-reporting-engine/pentaho-reporting-engine-wizard-core/3.9.1-GA/671508e5f7b038b19ddbdf34914eab87bbb646ee/pentaho-reporting-engine-wizard-core-3.9.1-GA.jar!/loader.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-library/libdocbundle/1.2.8/9bde3c7aa2154a08e6c7bfdfd6d35dc3b18d05aa/libdocbundle-1.2.8.jar!/loader.properties
    jar:file:/C:/Users/Guchie/.gradle/caches/modules-2/files-2.1/pentaho-library/libxml/1.2.8/60a57221b2f5b3ac5e8822bf14001640738a6ab/libxml-1.2.8.jar!/loader.properties

	at org.apache.fineract.infrastructure.classdupes.ClasspathHellDuplicatesCheckExtension.checkClasspath(ClasspathHellDuplicatesCheckExtension.java:64)
	at org.apache.fineract.infrastructure.classdupes.ClasspathHellDuplicatesCheckExtension.afterEach(ClasspathHellDuplicatesCheckExtension.java:58)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:255)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:271)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:271)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:270)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:254)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:143)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by bharathcgowda** [comment]
can you check with @luisalegria  once?
He should be able to help you out.

**Comment by francisguchie** [comment]
@luisalegria 

I am almost there (in my view but i am challenged with a duplicate class path exception)

**Comment by luisalegria** [comment]
Hi all

@francisguchie could you please give more detail. I understand that you were trying to add support at fineract lastest build (to develop branch)?

Or are you working on Bharath's fork (19.12.01 code base)?

Some minutes ago, I build Bharath's fork with pentaho support and it works (https://github.com/bharathcgowda/Fineract.git)

I did this steps:
$ git clone https://github.com/bharathcgowda/Fineract.git
$ cd Fineract/fineract-provider
$ gradle clean dist
And then, I search WAR file on Fineract/build/libs/ folder

Then, I updated c:\tomcat\webapps\ folder (be sure tomcat doesn't running):
* First, delete fineract-provider folder and fineract-provider.war
* Then copy new WAR file inside webapps folder
* Launch tomcat

Please, let me now if this could help you.

Best regards

**Comment by luisalegria** [comment]
I forgot this, I'm using this gradle version:
$ gradle --version

------------------------------------------------------------
Gradle 6.2
------------------------------------------------------------

Build time:   2020-02-17 08:32:01 UTC
Revision:     61d3320259a1a0d31519bf208eb13741679a742f

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_241 (Oracle Corporation 25.241-b07)
OS:           Windows 10 10.0 amd64

**Comment by francisguchie** [comment]
Dear Luis,

I would like to use the latest build i am NOT using this   (
https://github.com/bharathcgowda/Fineract.git)
As for the steps, i use the same steps when u make changes to the builds i
use



My Kind Regards

Francis Guchie Kirago
*Skype:* francisguchie
*Whatsapp: *232 79 19 44 07
*LINKEDIN:* https://www.linkedin.com/in/francis-guchie-kirago-a4379617/
twitter: @FrancisGuchie
